FROM sonar-scanner-image:latest AS sonarqube_scan
WORKDIR /app
COPY . .
RUN ls -flarts
RUN sonar-scanner \
    -Dsonar.host.url="http://localhost:9000" \
    -Dsonar.projectKey="c7921946865a4bdf1e3e76bbcfa6bf6dbed1a1f4" \
    -Dsonar.sources="."